### ISSUE TITLE
Update use of paho-mqtt

### ISSUE THREAD

**Issue by ggoforth** [pushy-me/pushy-python#1]
Following the Python SDK directions, I installed pushy via requirements.txt.  It installs fine, but immediatly errors upon importing the pushy api with the following error:

```
>>> import pushy
Exception ignored in: <function Client.__del__ at 0xffff80635ea0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/pushy/__init__.py", line 2, in <module>
    import pushy.lib.mqtt as mqtt
  File "/usr/local/lib/python3.10/site-packages/pushy/lib/mqtt.py", line 10, in <module>
    client = mqtt.Client()
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'
```

It looks like version 2.0 is what you get when you install pushy via pip, which breaks the python pushy sdk.  Confirmed by installing paho-mqtt#1.6.1 and the pushy modules import properly.

**Comment by pushy** [comment]
Hi @ggoforth,
Thanks so much for reporting this, and for helping us resolve this issue!

Merged & published your PR #2 to PyPI as version [`1.0.10`](https://pypi.org/project/pushy-python/). Please update to the latest version by running this command:

```
pip install --upgrade pushy-python
```
